MARKET: SNP

LOGLEVEL: ERROR

MAX_FILE_AGE: 0.5

COVER_STD_MULT: 0.9
COVER_MIN_DTE: 4
PROTECTION_STRIP: 1 # strike down for longs and up for shorts
MINEXPOPTPRICE: 0.2

# NSE ports and client IDs
PORT: 1300
PAPER: 1301

CID: 10