MARKET: SNP

LOGLEVEL: ERROR

MAXDTE: 35
NAKED_STD_MULT: 1.2
COVER_STD_MULT: 0.8
PROTECT_STD_MULT: 0.8

MINEXPROM: 1.05
MARGINPERORDER: 15000


# NSE ports and client IDs
PORT: 1300
PAPER: 1301

CID: 10